#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons
#
ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
#
FONT="Hack Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
# # SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components
#
PADDINGS=3 # All paddings use this value (icon, label, background)
#
POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

Setting up the general bar appearance and default values
sketchybar --bar     height=30                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=top                                     \
                     sticky=on                                         \
                     padding_right=18                                  \
                     padding_left=18                                   \
                     corner_radius=15                                   \
                     y_offset=4                                       \
                     margin=10                                         \
                     blur_radius=10                                    \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/window.sh"


sketchybar --add bracket left.island_bracket \
  $(for sid in $(aerospace list-workspaces --all); do echo -n "space.$sid "; done) \
  window.title \

sketchybar --set left.island_bracket \
    position=left \
    background.color=$BAR_COLOR \
    background.corner_radius=12 \
    background.blur_radius=10 \
    background.drawing=on \
    padding_left=100 \
    padding_right=15 \
    background.padding_left=100 \
    label.color=0xffffffff \
    label.font="Menlo:Bold:13.0" \
    background.height=30 \
    --update

#
#
# sketchybar --add item right.island right \
#   --set right.island \
#     background.color=$BAR_COLOR \
#     background.corner_radius=12 \
#     background.drawing=on \
#     padding_left=15 \
#     padding_right=15 \
#     label="$(date '+%H:%M')" \
#     label.color=0xffffffff \
#     label.font="Menlo:Bold:13.0" \
#     update_freq=60 \
#
# sketchybar --add item hello.label
# sketchybar --set hello.label label="Hello World" label.font="Menlo:12.0" label.color=0xffffffff
#
# sketchybar --add bracket hello.bracket hello.label
# sketchybar --set hello.bracket \
#   position=left \
#   background.color=0xee1e1e2e \
#   background.drawing=on \
#   background.corner_radius=10 \
#   padding_left=10 \
#   padding_right=10

# Center
# source "$ITEM_DIR/spotify.sh"

# Right
# System monitoring items
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/date.sh"


sketchybar --add item separator right \
  --set separator \
  label="|" \
  padding_right=14

 sketchybar --add item battery right \
  --set battery \
  script="$PLUGIN_DIR/battery.sh" \
  update_freq=60 

 sketchybar --add item system_cpu right \
           --set system_cpu \
             icon="󰻠" \
             icon.color=$ICON_COLOR \
             label.color=$LABEL_COLOR \
             script="$PLUGIN_DIR/system_cpu.sh" \
             update_freq=5 \
           --add item system_ram right \
           --set system_ram \
             icon="󰍛" \
             icon.color=$ICON_COLOR \
             label.color=$LABEL_COLOR \
             script="$PLUGIN_DIR/system_ram.sh" \
             update_freq=5 \

#



sketchybar --hotload true

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
